# Generated by Django 3.2 on 2021-04-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('curative_effects', models.CharField(max_length=200)),
                ('side_effects', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='essential_oils')),
            ],
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('essential_oil', models.ManyToManyField(blank=True, related_name='way', to='advice.EssentialOil')),
            ],
        ),
        migrations.CreateModel(
            name='MethodOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('way', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advice.way')),
            ],
        ),
        migrations.AddField(
            model_name='essentialoil',
            name='pathology',
            field=models.ManyToManyField(blank=True, related_name='essential_oil', to='advice.Pathology'),
        ),
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('essential_oil', models.ManyToManyField(blank=True, related_name='contraindication', to='advice.EssentialOil')),
            ],
        ),
    ]
