# Generated by Django 3.2 on 2021-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essentialoil',
            name='curative_effects',
        ),
        migrations.RemoveField(
            model_name='essentialoil',
            name='side_effects',
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('essential_oil', models.ManyToManyField(blank=True, related_name='side_effect', to='advice.EssentialOil')),
            ],
        ),
        migrations.CreateModel(
            name='CurativeEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('essential_oil', models.ManyToManyField(blank=True, related_name='curative_effect', to='advice.EssentialOil')),
            ],
        ),
    ]
