# Generated by Django 3.2 on 2021-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0003_methodofuse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='essential_oils')),
            ],
        ),
    ]
