# Generated by Django 3.2 on 2021-04-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_vegetableoil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='vegetable_oil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advice.vegetableoil'),
            preserve_default=False,
        ),
    ]
