# Generated by Django 3.2 on 2021-04-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_pathology_vegetable_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_he', models.IntegerField()),
                ('amount_he', models.CharField(max_length=200)),
                ('mount_hv', models.CharField(max_length=200)),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.way')),
            ],
        ),
    ]
