# Generated by Django 3.2 on 2021-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0006_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
