# Generated by Django 3.2 on 2021-04-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0007_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='pathology',
            field=models.ManyToManyField(blank=True, related_name='way', to='advice.Pathology'),
        ),
    ]
