# Generated by Django 3.2 on 2021-04-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0009_neutralproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodofuse',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.way'),
        ),
    ]
