# Generated by Django 3.2 on 2021-04-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0010_alter_methodofuse_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodofuse',
            name='way',
        ),
    ]
