# Generated by Django 3.2 on 2021-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0011_remove_methodofuse_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodofuse',
            name='quantity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
